[project]
name = "ml-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fiftyone>=1.10.0",
    "timm>=1.0.22",
    "torch>=2.9.1",
    "ultralytics>=8.3.228",
    "roboflow>=1.1.30",
]
